/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pyramid_solitare_jackfinlay.model.ui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import pyramid_solitare_jackfinlay.model.Card;

/**
 *
 * @author Jack
 */
public class CardGridPanel extends javax.swing.JPanel {

    private Card card = null;
    private BufferedImage cardImage;

    /**
     * Default constructor.
     */
    public CardGridPanel() {
        initComponents();
    }

    /**
     * Creates new form cardGridPanel
     *
     * @param card The card that this panel may possibly have.
     */
    public CardGridPanel(Card card) {
        initComponents();
        this.card = card;

        this.cardImage = this.card.getCardImage();
        
        Image resizedImage = cardImage.getScaledInstance(40, 58, java.awt.Image.SCALE_SMOOTH);
        this.cardImageLabel = new JLabel(new ImageIcon(resizedImage));
        this.removeAll();
        this.add(cardImageLabel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardImageLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(40, 60));
        setMinimumSize(new java.awt.Dimension(40, 60));
        setPreferredSize(new java.awt.Dimension(40, 60));

        cardImageLabel.setText("hfkjg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardImageLabel;
    // End of variables declaration//GEN-END:variables
}
